defmodule LiveFrames.Adapters.Bricks.StageA.CSSRenderer do
  @moduledoc """
  Renders the supported Bricks style subset and preserves source custom CSS.
  """

  alias LiveFrames.Adapters.Bricks.Serializer
  alias LiveFrames.Adapters.Bricks.Settings

  @header "/* Generated by LiveFrames Bricks Stage A pipeline; DO NOT EDIT. */"

  @spec render(map(), keyword()) :: String.t()
  def render(resolved, opts \\ [])

  def render(%{tree: tree, elements: elements}, _opts) do
    {rules, responsive, custom_css} =
      Enum.reduce(tree.ordered_elements, {[], [], %{base: [], responsive: []}}, fn element,
                                                                                   {rules,
                                                                                    responsive,
                                                                                    custom_css} ->
        resolved = Map.fetch!(elements, element.id)
        settings = Settings.extract(resolved.settings)
        rule = render_rule(element.id, element.name, settings)

        responsive =
          responsive ++ Enum.map(settings.responsive, &Map.put_new(&1, :source_id, element.id))

        custom_css = %{
          base:
            custom_css.base ++
              Enum.map(settings.custom_css.base, &%{source_id: element.id, value: &1}),
          responsive:
            custom_css.responsive ++
              Enum.map(settings.custom_css.responsive, &Map.put_new(&1, :source_id, element.id))
        }

        {if(rule == "", do: rules, else: rules ++ [rule]), responsive, custom_css}
      end)

    parts =
      [
        @header,
        Enum.join(rules, "\n\n"),
        render_custom_css(custom_css.base),
        render_responsive(responsive)
      ]
      |> Enum.reject(&(&1 == ""))

    Enum.join(parts, "\n\n") <> "\n"
  end

  def render(_resolved, _opts), do: @header <> "\n"

  defp render_rule(id, "image", settings) do
    base_styles = Map.drop(settings.base_styles, ["object-fit", "object-position"])
    base_rule = render_rule_for(scope_class(id), base_styles, settings.gradients)

    object_rule =
      render_rule_for(
        "#{scope_class(id)} img",
        Map.take(settings.base_styles, ["object-fit", "object-position"]),
        []
      )

    [base_rule, object_rule]
    |> Enum.reject(&(&1 == ""))
    |> Enum.join("\n\n")
  end

  defp render_rule(id, _element_name, settings),
    do: render_rule_for(scope_class(id), settings.base_styles, settings.gradients)

  defp render_rule_for(selector, base_styles, gradients) do
    declarations =
      base_styles
      |> Enum.sort_by(fn {property, _value} -> property end)
      |> Enum.map(fn {property, value} -> "  #{property}: #{value};" end)

    gradient_declarations =
      gradients
      |> Enum.map(&gradient_declaration/1)
      |> Enum.reject(&is_nil/1)
      |> Enum.map(&"  background-image: #{&1};")

    declarations = declarations ++ gradient_declarations

    if declarations == [] do
      ""
    else
      "#{selector_prefix(selector)} {\n#{Enum.join(declarations, "\n")}\n}"
    end
  end

  defp render_custom_css(base) do
    base
    |> Enum.map(& &1.value)
    |> Enum.map(&normalize_custom_css/1)
    |> Enum.join("\n")
    |> String.trim_trailing()
  end

  defp normalize_custom_css(value) when is_binary(value),
    do: Regex.replace(~r/[ \t]+$/m, value, "")

  defp normalize_custom_css(value), do: to_string(value)

  defp render_responsive(responsive) do
    responsive
    |> Enum.map(fn record ->
      raw =
        record
        |> Map.get(:raw_value, Map.get(record, :value))
        |> Serializer.encode!()
        |> sanitize_comment()

      property = record |> Map.get(:property) || "custom-css"
      source_key = record |> Map.get(:source_key, "unknown") |> to_string() |> sanitize_comment()
      source_id = record |> Map.get(:source_id, "unknown") |> to_string() |> sanitize_comment()
      breakpoint = record |> Map.get(:breakpoint, "unknown") |> to_string() |> sanitize_comment()

      "/* Bricks responsive source preserved; breakpoint=#{breakpoint}; source_id=#{source_id}; source_key=#{source_key}; property=#{property}; threshold=unresolved; raw=#{raw} */"
    end)
    |> Enum.join("\n")
  end

  defp gradient_declaration(%{value: value}), do: gradient_to_css(value)
  defp gradient_declaration(_record), do: nil

  defp gradient_to_css(value) when is_map(value) do
    type = Map.get(value, "gradientType", "linear")
    angle = gradient_angle(Map.get(value, "angle"))
    colors = Map.get(value, "colors")

    if type in ["linear", nil] and is_binary(angle) and is_list(colors) do
      stops = Enum.map(colors, &gradient_stop/1)

      if Enum.all?(stops, &is_binary/1) and stops != [] do
        "linear-gradient(#{angle}, #{Enum.join(stops, ", ")})"
      else
        nil
      end
    else
      nil
    end
  end

  defp gradient_to_css(_value), do: nil

  defp gradient_angle(value) when is_integer(value), do: "#{value}deg"
  defp gradient_angle(value) when is_float(value), do: "#{value}deg"

  defp gradient_angle(value) when is_binary(value) do
    if Regex.match?(~r/^[-+]?\d+(?:\.\d+)?$/, value), do: "#{value}deg", else: nil
  end

  defp gradient_angle(_value), do: nil

  defp gradient_stop(color) when is_map(color) do
    raw = get_in(color, ["color", "raw"])
    stop = Map.get(color, "stop")

    if safe_color?(raw) and is_valid_stop?(stop), do: "#{raw} #{normalize_stop(stop)}", else: nil
  end

  defp gradient_stop(_color), do: nil

  defp is_valid_stop?(value) when is_integer(value), do: true
  defp is_valid_stop?(value) when is_float(value), do: true

  defp is_valid_stop?(value) when is_binary(value),
    do: Regex.match?(~r/^[-+]?\d+(?:\.\d+)?%?$/, value)

  defp is_valid_stop?(_value), do: false

  defp normalize_stop(value) when is_integer(value), do: "#{value}%"
  defp normalize_stop(value) when is_float(value), do: "#{value}%"

  defp normalize_stop(value) when is_binary(value),
    do: if(String.ends_with?(value, "%"), do: value, else: "#{value}%")

  defp safe_color?(value) when is_binary(value) do
    lowered = String.downcase(value)
    value != "" and not String.contains?(lowered, ["{", "}", ";", "</", "url(", "javascript:"])
  end

  defp safe_color?(_value), do: false

  defp scope_class(id) when is_binary(id) do
    if Regex.match?(~r/^[A-Za-z0-9_-]+$/, id),
      do: "bricks-element--#{id}",
      else: "bricks-element--source"
  end

  defp scope_class(_id), do: "bricks-element--source"

  defp selector_prefix(selector), do: ".#{selector}"

  defp sanitize_comment(value), do: String.replace(value, "*/", "* /")
end
