defmodule LiveFrames.Adapters.Bricks.StageA.HTMLRenderer do
  @moduledoc """
  Renders the validated Bricks tree as escaped, standalone Stage A HTML.
  """

  @heading_tags ~w(h1 h2 h3 h4 h5 h6)
  @text_tags ~w(p span div)
  @safe_class ~r/^[A-Za-z_][A-Za-z0-9_-]*$/
  @safe_scope_segment ~r/^[A-Za-z0-9_-]+$/
  @header "<!-- Generated by LiveFrames Bricks Stage A pipeline; DO NOT EDIT. -->"

  @spec render(map(), keyword()) :: String.t()
  def render(resolved, opts \\ [])

  def render(%{tree: tree, elements: elements}, opts) do
    title = opts |> Keyword.get(:title, "Bricks Stage A") |> to_string() |> escape()
    stylesheet = opts |> Keyword.get(:stylesheet, "styles.css") |> to_string() |> escape()

    roots =
      tree.root_ids
      |> Enum.map(&render_node(&1, 1, tree, elements))
      |> Enum.join("\n")

    [
      @header,
      "<!doctype html>",
      "<html lang=\"en\">",
      "<head>",
      "  <meta charset=\"utf-8\">",
      "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
      "  <title>#{title}</title>",
      "  <link rel=\"stylesheet\" href=\"#{stylesheet}\">",
      "</head>",
      "<body>",
      roots,
      "</body>",
      "</html>"
    ]
    |> Enum.join("\n")
    |> Kernel.<>("\n")
  end

  def render(_resolved, _opts), do: @header <> "\n<!doctype html>\n<html lang=\"en\"></html>\n"

  defp render_node(id, depth, tree, elements) do
    resolved = Map.fetch!(elements, id)
    element = resolved.element
    settings = resolved.settings
    prefix = String.duplicate("  ", depth)
    classes = resolved.class_names ++ [scope_class(element.id)]
    class_attribute = " class=\"#{escape(Enum.join(Enum.map(classes, &safe_class/1), " "))}\""
    children = Map.get(tree.children_by_id, id, [])

    case element.name do
      "section" ->
        render_container(
          "section",
          class_attribute,
          children,
          settings,
          depth,
          tree,
          elements,
          prefix
        )

      name when name in ["container", "div"] ->
        render_container(
          "div",
          class_attribute,
          children,
          settings,
          depth,
          tree,
          elements,
          prefix
        )

      "heading" ->
        render_text_element(
          valid_heading_tag(settings["tag"]),
          class_attribute,
          settings["text"],
          prefix
        )

      "text-basic" ->
        render_text_element(
          valid_text_tag(settings["tag"]),
          class_attribute,
          settings["text"],
          prefix
        )

      "button" ->
        render_button(class_attribute, settings, prefix)

      "image" ->
        render_image(class_attribute, settings, prefix)

      unsupported ->
        render_unsupported(unsupported, class_attribute, prefix)
    end
  end

  defp render_container(tag, class_attribute, children, settings, depth, tree, elements, prefix) do
    text = if is_binary(settings["text"]), do: escape(settings["text"]), else: nil
    open = "#{prefix}<#{tag}#{class_attribute}>"

    cond do
      children != [] ->
        rendered_children =
          Enum.map(children, &render_node(&1, depth + 1, tree, elements)) |> Enum.join("\n")

        "#{open}\n#{rendered_children}\n#{prefix}</#{tag}>"

      is_binary(text) ->
        "#{open}#{text}</#{tag}>"

      true ->
        "#{open}</#{tag}>"
    end
  end

  defp render_text_element(tag, class_attribute, text, prefix) do
    text = if is_binary(text), do: escape(text), else: ""
    "#{prefix}<#{tag}#{class_attribute}>#{text}</#{tag}>"
  end

  defp render_button(class_attribute, settings, prefix) do
    text = settings |> Map.get("text", "") |> to_string() |> escape()

    case safe_link(settings) do
      {:ok, href} -> "#{prefix}<a#{class_attribute} href=\"#{escape(href)}\">#{text}</a>"
      :none -> "#{prefix}<button type=\"button\"#{class_attribute}>#{text}</button>"
    end
  end

  defp render_image(class_attribute, settings, prefix) do
    image = Map.get(settings, "image", %{})
    url = Map.get(image, "url")
    src = if is_binary(url) and safe_url?(url), do: url, else: "about:blank"
    alt = image |> Map.get("alt", Map.get(settings, "alt", "")) |> to_string() |> escape()
    attachment = Map.get(image, "id")

    attachment_attribute =
      if is_integer(attachment), do: " data-bricks-attachment-id=\"#{attachment}\"", else: ""

    image_tag = "<img src=\"#{escape(src)}\" alt=\"#{alt}\"#{attachment_attribute}>"

    if settings["tag"] == "figure" do
      "#{prefix}<figure#{class_attribute}>#{image_tag}</figure>"
    else
      "#{prefix}<div#{class_attribute}>#{image_tag}</div>"
    end
  end

  defp render_unsupported(name, class_attribute, prefix) do
    "#{prefix}<div#{class_attribute} data-bricks-unsupported=\"#{escape(name)}\"></div>"
  end

  defp safe_link(settings) do
    url =
      case Map.get(settings, "url") do
        value when is_binary(value) -> value
        _ -> get_in(settings, ["link", "url"])
      end

    if is_binary(url) and safe_url?(url), do: {:ok, url}, else: :none
  end

  defp safe_url?(url), do: not Regex.match?(~r/\A(?:javascript|data|vbscript):/i, url)

  defp valid_heading_tag(tag) when tag in @heading_tags, do: tag
  defp valid_heading_tag(_tag), do: "h2"

  defp valid_text_tag(tag) when tag in @text_tags, do: tag
  defp valid_text_tag(_tag), do: "p"

  defp scope_class(id) when is_binary(id) do
    if Regex.match?(@safe_scope_segment, id),
      do: "bricks-element--#{id}",
      else: "bricks-element--source"
  end

  defp scope_class(_id), do: "bricks-element--source"

  defp safe_class(value) when is_binary(value) do
    if Regex.match?(@safe_class, value), do: value, else: "bricks-source-class"
  end

  defp safe_class(_value), do: "bricks-source-class"

  defp escape(value) do
    value
    |> String.replace("&", "&amp;")
    |> String.replace("<", "&lt;")
    |> String.replace(">", "&gt;")
    |> String.replace("\"", "&quot;")
    |> String.replace("'", "&#39;")
  end
end
